"use client";

// SudokuDemo.tsx
//
// Top-level client component for /demo/sudoku. Fetches the evidence
// payload generated by `mosaic-demo-sudoku::generate-fixtures` and
// renders:
//   - hero strip with Mosaic mark
//   - interactive puzzle grid (hover any cell to highlight the row,
//     column, and 3×3 box that cell's solution value participates
//     in via the circuit's group-sum constraints)
//   - constraint-count instrumentation
//   - cryptographic provenance grid
//   - proof byte anatomy (interactive — hover/click a 32-byte chunk
//     to see which BN254 group element it encodes)
//   - verification terminal (replay of captured Mosaic verifier
//     output for the valid + tampered proof bytes)
//   - multi-system comparison: same Mosaic library verifying a
//     snarkjs-emitted PLONK fixture, addressing the "could we use
//     PLONK instead?" question with real numbers
//
// All real data; no mock. Every byte and timing on this page is
// produced by the workspace at this commit.

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";

import { AnimatedSpan, Terminal, TypingAnimation } from "../../components/Terminal";

const EVIDENCE_PATH = "/demo/sudoku/evidence.json";

interface ConstraintBreakdownJson {
  in_range_chain: number;
  in_range_terminator: number;
  square_allocation: number;
  clue_match: number;
  clue_match_zero: number;
  group_sum: number;
  group_sum_of_squares: number;
  total: number;
}

interface Timings {
  setup_ms: number;
  prove_ms: number;
  verify_arkworks_ms: number;
  verify_mosaic_valid_ms: number;
  verify_mosaic_tampered_ms: number;
}

interface Sizes {
  vk: number;
  proof: number;
  public_inputs: number;
}

interface Digests {
  vk: string;
  proof_valid: string;
  proof_tampered: string;
  public_inputs: string;
  puzzle: string;
}

interface VerifierOutcomes {
  arkworks_valid: string;
  mosaic_valid: string;
  mosaic_tampered: string;
}

interface PlonkDigests {
  vk: string;
  proof: string;
  public_inputs: string;
}

interface PlonkComparison {
  artifact_root: string;
  prover_source: string;
  circuit: string;
  verify_ms: number;
  outcome: string;
  sizes_bytes: Sizes;
  digests_sha256: PlonkDigests;
  onchain_cu_baseline: number;
}

interface Evidence {
  schema_version: number;
  generated_at: string;
  workspace_version: string;
  repo_commit_sha: string;
  puzzle_source: string;
  puzzle: number[];
  solution: number[];
  clue_count: number;
  constraint_breakdown: ConstraintBreakdownJson;
  constraint_count: number;
  public_input_count: number;
  setup_seed: string;
  prove_seed: string;
  timings: Timings;
  sizes_bytes: Sizes;
  digests_sha256: Digests;
  verifier_outcomes: VerifierOutcomes;
  plonk_comparison: PlonkComparison | null;
}

function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KiB`;
  return `${(n / 1024 / 1024).toFixed(2)} MiB`;
}

function formatMs(ms: number): string {
  if (ms < 1) return "<1 ms";
  if (ms < 1000) return `${ms} ms`;
  return `${(ms / 1000).toFixed(2)} s`;
}

function formatNumber(n: number): string {
  return n.toLocaleString("en-US");
}

// ── Cell coordinate helpers for the grid-hover highlight system ──

function rowOf(idx: number): number {
  return Math.floor(idx / 9);
}
function colOf(idx: number): number {
  return idx % 9;
}
function boxOf(idx: number): number {
  const r = rowOf(idx);
  const c = colOf(idx);
  return Math.floor(r / 3) * 3 + Math.floor(c / 3);
}
function isInSameGroupAs(focus: number, idx: number): boolean {
  if (focus < 0) return false;
  return (
    rowOf(idx) === rowOf(focus) ||
    colOf(idx) === colOf(focus) ||
    boxOf(idx) === boxOf(focus)
  );
}

// ── Groth16 proof anatomy: 256 bytes = 8 chunks of 32 bytes ───────
//
// Layout per `mosaic_serde::arkworks::ArkworksCodec::encode_proof`:
//   bytes 0..32   A.x  (G1 affine x)
//   bytes 32..64  A.y  (G1 affine y)
//   bytes 64..96  B.x.c1 (G2 affine x, Fq2 imaginary component)
//   bytes 96..128 B.x.c0 (G2 affine x, Fq2 real component)
//   bytes 128..160 B.y.c1 (G2 affine y, Fq2 imaginary component)
//   bytes 160..192 B.y.c0 (G2 affine y, Fq2 real component)
//   bytes 192..224 C.x  (G1 affine x)
//   bytes 224..256 C.y  (G1 affine y)
//
// Each component is a big-endian BN254 base-field element (Fq, 254
// bits → 32 bytes). Solana's alt_bn128 syscall consumes this layout
// verbatim.

const PROOF_CHUNK_SPEC: Array<{
  label: string;
  field: string;
  range: [number, number];
  group: "A" | "B" | "C";
  description: string;
}> = [
  {
    label: "A.x",
    field: "G1 affine x-coordinate (Fq, BE)",
    range: [0, 32],
    group: "A",
    description:
      "Half of the witness commitment A ∈ G1. arkworks sets A from the multi-scalar-multiplication of the witness vector with the proving key's α-row.",
  },
  {
    label: "A.y",
    field: "G1 affine y-coordinate (Fq, BE)",
    range: [32, 64],
    group: "A",
    description:
      "The y-coordinate. Together with A.x this is one BN254 G1 point; the verifier checks it lies on the curve via the alt_bn128 syscall.",
  },
  {
    label: "B.x.c1",
    field: "G2 affine x (Fq2 imaginary)",
    range: [64, 96],
    group: "B",
    description:
      "B ∈ G2 is a point over Fq2 = Fq[u]/(u² + 1). Solana's alt_bn128 layout orders Fq2 as c1 ‖ c0, the reverse of arkworks' native c0 ‖ c1 — see ADR-0003 for the swap rationale.",
  },
  {
    label: "B.x.c0",
    field: "G2 affine x (Fq2 real)",
    range: [96, 128],
    group: "B",
    description:
      "Real component of B.x. Mosaic's ArkworksCodec rewrites arkworks little-endian to Mosaic big-endian here.",
  },
  {
    label: "B.y.c1",
    field: "G2 affine y (Fq2 imaginary)",
    range: [128, 160],
    group: "B",
    description:
      "Imaginary component of B.y. The verifier's pairing check e(A, B) = e(α, β)·e(L, γ)·e(C, δ) consumes both Fq2 elements.",
  },
  {
    label: "B.y.c0",
    field: "G2 affine y (Fq2 real)",
    range: [160, 192],
    group: "B",
    description:
      "Real component of B.y. Together with B.y.c1 this completes the G2 affine y-coordinate.",
  },
  {
    label: "C.x",
    field: "G1 affine x-coordinate (Fq, BE)",
    range: [192, 224],
    group: "C",
    description:
      "C ∈ G1 absorbs the rest of the linear combination. C and the public-input commitment L jointly close the pairing check.",
  },
  {
    label: "C.y",
    field: "G1 affine y-coordinate (Fq, BE)",
    range: [224, 256],
    group: "C",
    description:
      "Final 32 bytes. If a single bit in this region flips, the verifier returns Err(PointNotOnCurve) or Err(PairingCheckFailed) depending on whether the corrupted point still lies on the curve.",
  },
];

function shortHash(h: string): string {
  if (h.length <= 16) return h;
  return `${h.slice(0, 8)}…${h.slice(-8)}`;
}

function clampLines(stdout: string, max = 28): string[] {
  const lines = stdout.split("\n");
  if (lines.length <= max) return lines;
  const head = Math.floor(max / 2);
  const tail = max - head - 1;
  return [
    ...lines.slice(0, head),
    `    ... [${lines.length - max} lines collapsed]`,
    ...lines.slice(lines.length - tail),
  ];
}

export function SudokuDemo() {
  const [evidence, setEvidence] = useState<Evidence | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showSolution, setShowSolution] = useState(false);
  const [focusedCell, setFocusedCell] = useState<number>(-1);
  const [activeReplay, setActiveReplay] = useState<"valid" | "tampered">(
    "valid",
  );
  const [generation, setGeneration] = useState(0);
  // Proof anatomy: which chunk (0..8) is the visitor focusing on.
  const [proofFocus, setProofFocus] = useState<number>(-1);
  // Live proof-byte hex: parsed once the proof.bin loads.
  const [proofHex, setProofHex] = useState<string[] | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(EVIDENCE_PATH, { cache: "no-store" })
      .then((r) => {
        if (!r.ok) throw new Error(`${EVIDENCE_PATH}: HTTP ${r.status}`);
        return r.json() as Promise<Evidence>;
      })
      .then((p) => {
        if (!cancelled) setEvidence(p);
      })
      .catch((e) => {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  // Fetch the raw proof bytes so the anatomy panel can show real hex,
  // not placeholders. 256 bytes → 8 chunks of 32 bytes → 64 hex chars
  // per chunk.
  useEffect(() => {
    let cancelled = false;
    fetch("/demo/sudoku/proof_valid.bin", { cache: "no-store" })
      .then((r) => (r.ok ? r.arrayBuffer() : Promise.reject(`HTTP ${r.status}`)))
      .then((buf) => {
        if (cancelled) return;
        const view = new Uint8Array(buf);
        const chunks: string[] = [];
        for (let i = 0; i < view.byteLength; i += 32) {
          const slice = view.slice(i, i + 32);
          let hex = "";
          for (const b of slice) hex += b.toString(16).padStart(2, "0");
          chunks.push(hex);
        }
        setProofHex(chunks);
      })
      .catch(() => {
        if (!cancelled) setProofHex(null);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const cells = useMemo(() => {
    if (!evidence) return [] as number[];
    return showSolution ? evidence.solution : evidence.puzzle;
  }, [evidence, showSolution]);

  if (error) {
    return (
      <div className="demo-error">
        <p>Could not load /demo/sudoku evidence: {error}.</p>
        <p>
          Run <code>cargo run -p mosaic-demo-sudoku --bin generate-fixtures --release</code>{" "}
          from the repo root to regenerate.
        </p>
      </div>
    );
  }

  if (!evidence) {
    return <div className="demo-loading">Loading evidence…</div>;
  }

  const cb = evidence.constraint_breakdown;
  const constraintRows: Array<[string, string, number]> = [
    ["In-range chain", "p_k = p_{k-1} · (v − k)  for v ∈ {1..9}", cb.in_range_chain],
    ["In-range terminator", "p_9 · 1 = 0", cb.in_range_terminator],
    ["Square allocation", "sq = v · v", cb.square_allocation],
    ["Clue match", "clue · (clue − sol) = product", cb.clue_match],
    ["Clue match zero", "product · 1 = 0", cb.clue_match_zero],
    ["Group sum", "Σ v · 1 = 45 · 1   for each row/col/box", cb.group_sum],
    ["Group sum-of-squares", "Σ sq · 1 = 285 · 1   for each row/col/box", cb.group_sum_of_squares],
  ];

  const digestRows: Array<{
    label: string;
    digest: string;
    artifact: string;
    size: string;
  }> = [
    {
      label: "Verifying Key",
      digest: evidence.digests_sha256.vk,
      artifact: "/demo/sudoku/vk.bin",
      size: formatBytes(evidence.sizes_bytes.vk),
    },
    {
      label: "Proof (valid)",
      digest: evidence.digests_sha256.proof_valid,
      artifact: "/demo/sudoku/proof_valid.bin",
      size: formatBytes(evidence.sizes_bytes.proof),
    },
    {
      label: "Proof (tampered)",
      digest: evidence.digests_sha256.proof_tampered,
      artifact: "/demo/sudoku/proof_tampered.bin",
      size: formatBytes(evidence.sizes_bytes.proof),
    },
    {
      label: "Public inputs",
      digest: evidence.digests_sha256.public_inputs,
      artifact: "/demo/sudoku/public_inputs.bin",
      size: formatBytes(evidence.sizes_bytes.public_inputs),
    },
    {
      label: "Puzzle",
      digest: evidence.digests_sha256.puzzle,
      artifact: "#",
      size: `${evidence.public_input_count} cells`,
    },
  ];

  const onReplay = (which: "valid" | "tampered") => {
    if (which === activeReplay) {
      setGeneration((g) => g + 1);
      return;
    }
    setActiveReplay(which);
    setGeneration((g) => g + 1);
  };

  const isValid = activeReplay === "valid";
  const replayLines = isValid
    ? buildValidReplay(evidence)
    : buildTamperedReplay(evidence);
  const replayCommand = isValid
    ? "cargo test -p mosaic-demo-sudoku end_to_end_setup_prove_verify_via_mosaic"
    : "cargo test -p mosaic-demo-sudoku tampered_proof_rejects_via_mosaic";

  const versionLabel = `v${evidence.workspace_version}`;
  const focusedChunk =
    proofFocus >= 0 && proofFocus < PROOF_CHUNK_SPEC.length
      ? PROOF_CHUNK_SPEC[proofFocus]
      : null;

  const plonk = evidence.plonk_comparison;

  return (
    <div className="demo-stack">
      {/* Hero. */}
      <header className="demo-hero">
        <div className="demo-hero-mark">
          <Image
            src="/assets/mosaic.webp"
            alt="Mosaic circular tessellation mark"
            width={600}
            height={600}
            priority
          />
        </div>
        <div className="demo-hero-text">
          <span className="tag">MOSAIC // DEMO 01 // ZK-SUDOKU</span>
          <h1 className="display">ZK-Sudoku</h1>
          <p className="hero-sub">
            Prove knowledge of a sudoku solution without revealing it.
            Real arkworks Groth16 proof, verified by{" "}
            <strong>mosaic-groth16</strong> on the same byte format the
            on-chain dispatcher accepts.
          </p>
          <p className="body-copy">
            The artifacts on this page were generated by the{" "}
            <code className="inline-code">mosaic-demo-sudoku</code>{" "}
            workspace crate at commit{" "}
            <code className="inline-code">{evidence.repo_commit_sha}</code>{" "}
            against workspace version{" "}
            <code className="inline-code">{versionLabel}</code>.
            Reproduce locally:
          </p>
          <pre className="demo-repro">
            <code>
              cargo run -p mosaic-demo-sudoku --bin generate-fixtures --release
            </code>
          </pre>
          <a className="demo-back" href="/">
            ← back to the onepager
          </a>
        </div>
      </header>

      {/* Puzzle + circuit. */}
      <section className="demo-stage">
        <div className="demo-stage-grid">
          <header className="demo-stage-header">
            <span className="tag">PUZZLE</span>
            <h2 className="sub-display">{evidence.puzzle_source}</h2>
            <p className="body-copy">
              Hover any cell to see the row, column, and 3×3 box it
              participates in — those three groups generate the
              circuit's permutation constraints. The verifier sees
              only the {evidence.clue_count} clue cells; the other{" "}
              {81 - evidence.clue_count} are the prover's witness.
            </p>
          </header>
          <div className="demo-grid-wrap">
            <div className="demo-grid-labels">
              <div className="demo-grid-corner" />
              {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((n) => (
                <span key={`c${n}`} className="demo-grid-label">
                  {n}
                </span>
              ))}
            </div>
            <div className="demo-grid-row">
              <div className="demo-grid-rows">
                {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((n) => (
                  <span key={`r${n}`} className="demo-grid-label">
                    {n}
                  </span>
                ))}
              </div>
              <div
                className="demo-grid"
                onMouseLeave={() => setFocusedCell(-1)}
              >
                {cells.map((v, i) => {
                  const isClue = evidence.puzzle[i] !== 0;
                  const isFocus = focusedCell === i;
                  const inGroup =
                    focusedCell >= 0 && isInSameGroupAs(focusedCell, i);
                  const cls = [
                    "demo-cell",
                    isClue ? "demo-cell-clue" : "demo-cell-witness",
                    isFocus ? "demo-cell-focus" : "",
                    inGroup && !isFocus ? "demo-cell-in-group" : "",
                  ].join(" ");
                  const row = Math.floor(i / 9);
                  const col = i % 9;
                  const boxBorderCls = [
                    row % 3 === 0 ? "demo-cell-top" : "",
                    col % 3 === 0 ? "demo-cell-left" : "",
                    row === 8 ? "demo-cell-bottom" : "",
                    col === 8 ? "demo-cell-right" : "",
                  ]
                    .filter(Boolean)
                    .join(" ");
                  return (
                    <div
                      key={i}
                      className={`${cls} ${boxBorderCls}`}
                      onMouseEnter={() => setFocusedCell(i)}
                      onFocus={() => setFocusedCell(i)}
                      onBlur={() => setFocusedCell(-1)}
                      tabIndex={0}
                      role="button"
                      aria-label={`Cell row ${rowOf(i) + 1}, column ${colOf(i) + 1}${v === 0 ? "" : `, value ${v}`}`}
                    >
                      {v === 0 ? "" : v}
                    </div>
                  );
                })}
              </div>
            </div>
            <div className="demo-grid-readout">
              {focusedCell >= 0 ? (
                <FocusReadout
                  cellIdx={focusedCell}
                  cellValue={cells[focusedCell]}
                  isClue={evidence.puzzle[focusedCell] !== 0}
                />
              ) : (
                <p className="demo-grid-readout-empty">
                  Hover a cell to see its constraint participation.
                </p>
              )}
            </div>
            <div className="demo-grid-controls">
              <button
                type="button"
                className={`demo-toggle ${!showSolution ? "demo-toggle-active" : ""}`}
                onClick={() => setShowSolution(false)}
              >
                <span className="demo-toggle-label">Verifier&rsquo;s view</span>
                <span className="demo-toggle-sub">
                  {evidence.clue_count} public clues
                </span>
              </button>
              <button
                type="button"
                className={`demo-toggle ${showSolution ? "demo-toggle-active" : ""}`}
                onClick={() => setShowSolution(true)}
              >
                <span className="demo-toggle-label">Reveal solution</span>
                <span className="demo-toggle-sub">
                  Witness · zero-knowledge in production
                </span>
              </button>
            </div>
          </div>
        </div>

        <aside className="demo-aside">
          <header className="demo-aside-header">
            <span className="tag">CIRCUIT</span>
            <h2 className="sub-display">
              {evidence.constraint_count.toLocaleString()} R1CS constraints
            </h2>
          </header>
          <table className="demo-table">
            <thead>
              <tr>
                <th>Family</th>
                <th>Rule</th>
                <th>Count</th>
              </tr>
            </thead>
            <tbody>
              {constraintRows.map(([family, rule, count]) => (
                <tr key={family}>
                  <td>{family}</td>
                  <td className="demo-table-mono">{rule}</td>
                  <td className="demo-table-num">{count}</td>
                </tr>
              ))}
              <tr className="demo-table-total">
                <td colSpan={2}>Total</td>
                <td className="demo-table-num">{cb.total.toLocaleString()}</td>
              </tr>
            </tbody>
          </table>
        </aside>
      </section>

      {/* Provenance. */}
      <section className="demo-provenance">
        <header className="demo-provenance-header">
          <span className="tag">CRYPTOGRAPHIC PROVENANCE</span>
          <h2 className="sub-display">
            What the
            <br />
            verifier actually
            <br />
            consumes
          </h2>
          <p className="mag-lead">
            Every artifact below is a real file under{" "}
            <code className="inline-code">site/public/demo/sudoku/</code>.
            The SHA-256 digests reproduce byte-for-byte across runs —
            same commit, same seed, same hash. Click any row to
            inspect the raw bytes.
          </p>
        </header>
        <dl className="demo-digest-grid">
          {digestRows.map((row) => (
            <a
              key={row.label}
              className="demo-digest-row"
              href={row.artifact}
              download={row.artifact !== "#" ? undefined : false}
            >
              <dt>{row.label}</dt>
              <dd className="demo-digest-meta">{row.size}</dd>
              <dd className="demo-digest-hash">
                <code>{row.digest}</code>
              </dd>
            </a>
          ))}
        </dl>
        <div className="demo-timings">
          <dl>
            <div>
              <dt>Setup</dt>
              <dd>{formatMs(evidence.timings.setup_ms)}</dd>
            </div>
            <div>
              <dt>Prove</dt>
              <dd>{formatMs(evidence.timings.prove_ms)}</dd>
            </div>
            <div>
              <dt>Verify (arkworks)</dt>
              <dd>{formatMs(evidence.timings.verify_arkworks_ms)}</dd>
            </div>
            <div>
              <dt>Verify (Mosaic, valid)</dt>
              <dd>{formatMs(evidence.timings.verify_mosaic_valid_ms)}</dd>
            </div>
            <div>
              <dt>Verify (Mosaic, tampered)</dt>
              <dd>{formatMs(evidence.timings.verify_mosaic_tampered_ms)}</dd>
            </div>
          </dl>
        </div>
      </section>

      {/* Proof byte anatomy. */}
      <section className="demo-anatomy">
        <header className="demo-anatomy-header">
          <span className="tag">PROOF ANATOMY</span>
          <h2 className="sub-display">
            256 bytes — three
            <br />
            BN254 group elements
          </h2>
          <p className="mag-lead">
            The proof is exactly three points on the BN254 elliptic
            curve: <strong>A ∈ G1</strong>, <strong>B ∈ G2</strong>,{" "}
            <strong>C ∈ G1</strong>. Hover any chunk to see what it
            encodes. The byte hex is loaded live from{" "}
            <code className="inline-code">/demo/sudoku/proof_valid.bin</code>{" "}
            — the same bytes Mosaic accepted above.
          </p>
        </header>
        <div className="demo-anatomy-grid">
          {PROOF_CHUNK_SPEC.map((chunk, idx) => {
            const hex = proofHex?.[idx] ?? "?".repeat(64);
            const isFocus = proofFocus === idx;
            const cls = [
              "demo-chunk",
              `demo-chunk-${chunk.group}`,
              isFocus ? "demo-chunk-focus" : "",
            ].join(" ");
            return (
              <button
                key={chunk.label}
                type="button"
                className={cls}
                onMouseEnter={() => setProofFocus(idx)}
                onFocus={() => setProofFocus(idx)}
                onClick={() => setProofFocus(idx)}
              >
                <span className="demo-chunk-head">
                  <span className="demo-chunk-label">{chunk.label}</span>
                  <span className="demo-chunk-range">
                    bytes {chunk.range[0]}..{chunk.range[1]}
                  </span>
                </span>
                <code className="demo-chunk-hex">
                  {hex.slice(0, 16)}
                  <span className="demo-chunk-ellipsis"> … </span>
                  {hex.slice(-16)}
                </code>
              </button>
            );
          })}
        </div>
        <div className="demo-anatomy-detail">
          {focusedChunk ? (
            <>
              <span className="tag">{focusedChunk.label}</span>
              <h3>{focusedChunk.field}</h3>
              <p>{focusedChunk.description}</p>
            </>
          ) : (
            <p className="demo-anatomy-detail-empty">
              Hover or focus a chunk above to inspect what it encodes.
            </p>
          )}
        </div>
      </section>

      {/* Verify panel. */}
      <section className="demo-verify">
        <header className="demo-verify-header">
          <span className="tag">VERIFY</span>
          <h2 className="sub-display">
            Mosaic accepts
            <br />
            the real proof
          </h2>
          <p className="mag-lead">
            Two captures, both real. The valid proof is the byte
            sequence in <code className="inline-code">proof_valid.bin</code> —
            the Mosaic verifier returns <code className="inline-code">Ok(())</code>.
            The tampered proof has its low bit flipped at byte offset
            zero — Mosaic returns{" "}
            <code className="inline-code">Err(PointNotOnCurve)</code>{" "}
            deterministically, the same error path the on-chain
            dispatcher would emit.
          </p>
        </header>
        <div className="demo-verify-tabs">
          <button
            type="button"
            className={`demo-tab ${isValid ? "demo-tab-active" : ""}`}
            onClick={() => onReplay("valid")}
          >
            <span className="demo-tab-label">Verify valid proof</span>
            <span className="demo-tab-sub">
              expects Ok(()) · {formatMs(evidence.timings.verify_mosaic_valid_ms)}
            </span>
          </button>
          <button
            type="button"
            className={`demo-tab ${!isValid ? "demo-tab-active" : ""}`}
            onClick={() => onReplay("tampered")}
          >
            <span className="demo-tab-label">Verify tampered proof</span>
            <span className="demo-tab-sub">
              expects Err(...) · {formatMs(evidence.timings.verify_mosaic_tampered_ms)}
            </span>
          </button>
        </div>
        <Terminal
          sequence
          startOnView
          generation={generation}
          chromeLabel={`MOSAIC // DEMO 01 // ${isValid ? "VERIFY VALID" : "VERIFY TAMPERED"}`}
          chromeRight={`${evidence.repo_commit_sha} · ${versionLabel}`}
        >
          <AnimatedSpan
            key={`prompt-${activeReplay}-${generation}`}
            className="mtm-line-prompt"
          >
            <span className="mtm-prompt-host">mosaic@workspace</span>
            <span className="mtm-prompt-sep">:</span>
            <span className="mtm-prompt-path">
              ~/mosaic [{evidence.repo_commit_sha} demo/sudoku]
            </span>
            <span className="mtm-prompt-sep">$</span>
          </AnimatedSpan>
          <TypingAnimation
            key={`cmd-${activeReplay}-${generation}`}
            duration={11}
            className="mtm-line-cmd"
          >
            {replayCommand}
          </TypingAnimation>
          {clampLines(replayLines.join("\n"), 28).map((line, idx) => (
            <AnimatedSpan
              key={`out-${activeReplay}-${generation}-${idx}`}
              className="mtm-line-out"
            >
              {line === "" ? " " : line}
            </AnimatedSpan>
          ))}
          <AnimatedSpan
            key={`result-${activeReplay}-${generation}`}
            className="mtm-line-result"
          >
            {isValid
              ? `verifier returned Ok(()) · proved knowledge of solution without revealing it · ${formatMs(evidence.timings.verify_mosaic_valid_ms)} wall-clock`
              : `verifier returned ${evidence.verifier_outcomes.mosaic_tampered.replace("reject:", "Err(") + ")"} · soundness boundary intact · ${formatMs(evidence.timings.verify_mosaic_tampered_ms)} wall-clock`}
          </AnimatedSpan>
        </Terminal>
      </section>

      {/* Multi-system comparison. */}
      {plonk ? (
        <section className="demo-compare">
          <header className="demo-compare-header">
            <span className="tag">COULD WE HAVE USED PLONK?</span>
            <h2 className="sub-display">
              Yes — and the same
              <br />
              Mosaic library does.
            </h2>
            <p className="mag-lead">
              <code className="inline-code">mosaic-plonk</code> is a
              production verifier in the same workspace as{" "}
              <code className="inline-code">mosaic-groth16</code>. The
              row below is real: this build re-verifies a snarkjs PLONK
              0.7.6 proof through <code className="inline-code">mosaic-plonk</code>'s host backend
              at the same commit — same code path the SBF runtime
              executes on chain.
            </p>
            <p className="body-copy">
              Why Groth16 for the sudoku demo? Single-cargo-command
              build: arkworks ships a Rust-native Groth16 prover, so
              the entire pipeline (circuit → setup → prove → encode →
              verify) is one binary. A real PLONK sudoku would route
              through snarkjs (Node.js + CIRCOM toolchain) or gnark
              (Go), neither of which we want to require at build time.
              The PLONK fixture below shows the same{" "}
              <code className="inline-code">mosaic-plonk</code>{" "}
              verifier accepting a Rust-untouched, snarkjs-emitted
              proof.
            </p>
          </header>
          <div className="demo-compare-grid">
            <div className="demo-compare-col">
              <h3>Groth16 · BN254</h3>
              <dl>
                <div>
                  <dt>Crate</dt>
                  <dd>
                    <code>mosaic-groth16</code>
                  </dd>
                </div>
                <div>
                  <dt>Circuit</dt>
                  <dd>
                    Sudoku 9×9, {evidence.constraint_count.toLocaleString()} R1CS, {evidence.public_input_count}{" "}
                    public inputs
                  </dd>
                </div>
                <div>
                  <dt>Prover</dt>
                  <dd>arkworks Rust-native</dd>
                </div>
                <div>
                  <dt>Trusted setup</dt>
                  <dd>Per-circuit (seed pinned in this build)</dd>
                </div>
                <div>
                  <dt>VK size</dt>
                  <dd>{formatBytes(evidence.sizes_bytes.vk)}</dd>
                </div>
                <div>
                  <dt>Proof size</dt>
                  <dd>{formatBytes(evidence.sizes_bytes.proof)}</dd>
                </div>
                <div>
                  <dt>Host verify</dt>
                  <dd>{formatMs(evidence.timings.verify_mosaic_valid_ms)}</dd>
                </div>
                <div>
                  <dt>On-chain CU (pinned)</dt>
                  <dd>83 574 CU · single proof</dd>
                </div>
              </dl>
            </div>
            <div className="demo-compare-col">
              <h3>KZG-PLONK · BN254</h3>
              <dl>
                <div>
                  <dt>Crate</dt>
                  <dd>
                    <code>mosaic-plonk</code>
                  </dd>
                </div>
                <div>
                  <dt>Circuit</dt>
                  <dd>{plonk.circuit}</dd>
                </div>
                <div>
                  <dt>Prover</dt>
                  <dd>{plonk.prover_source}</dd>
                </div>
                <div>
                  <dt>Trusted setup</dt>
                  <dd>Universal (KZG ceremony)</dd>
                </div>
                <div>
                  <dt>VK size</dt>
                  <dd>{formatBytes(plonk.sizes_bytes.vk)}</dd>
                </div>
                <div>
                  <dt>Proof size</dt>
                  <dd>{formatBytes(plonk.sizes_bytes.proof)}</dd>
                </div>
                <div>
                  <dt>Host verify</dt>
                  <dd>{formatMs(plonk.verify_ms)}</dd>
                </div>
                <div>
                  <dt>On-chain CU (pinned)</dt>
                  <dd>{formatNumber(plonk.onchain_cu_baseline)} CU · single proof</dd>
                </div>
              </dl>
            </div>
          </div>
          <div className="demo-compare-footer">
            <p>
              <strong>The Mosaic library accepted both, this build.</strong>{" "}
              Groth16 returned <code>Ok(())</code> in{" "}
              {formatMs(evidence.timings.verify_mosaic_valid_ms)};
              KZG-PLONK returned <code>{plonk.outcome === "accept" ? "Ok(())" : plonk.outcome}</code>{" "}
              in {formatMs(plonk.verify_ms)}. The two proofs differ in
              circuit, prover toolchain, and on-chain cost — but the
              Mosaic dispatcher is identical for both.
            </p>
            <div className="demo-compare-digest">
              <div>
                <span className="demo-compare-digest-label">PLONK VK SHA-256</span>
                <code>{plonk.digests_sha256.vk}</code>
              </div>
              <div>
                <span className="demo-compare-digest-label">PLONK proof SHA-256</span>
                <code>{plonk.digests_sha256.proof}</code>
              </div>
              <div>
                <span className="demo-compare-digest-label">Artifacts</span>
                <span className="demo-compare-digest-links">
                  <a href={`${plonk.artifact_root}/vk.bin`}>vk.bin</a>
                  <a href={`${plonk.artifact_root}/proof.bin`}>proof.bin</a>
                  <a href={`${plonk.artifact_root}/public_inputs.bin`}>
                    public_inputs.bin
                  </a>
                </span>
              </div>
            </div>
          </div>
        </section>
      ) : null}
    </div>
  );
}

function FocusReadout({
  cellIdx,
  cellValue,
  isClue,
}: {
  cellIdx: number;
  cellValue: number;
  isClue: boolean;
}) {
  const r = rowOf(cellIdx) + 1;
  const c = colOf(cellIdx) + 1;
  const boxR = Math.floor(rowOf(cellIdx) / 3) + 1;
  const boxC = Math.floor(colOf(cellIdx) / 3) + 1;
  return (
    <dl className="demo-grid-readout-dl">
      <div>
        <dt>Cell</dt>
        <dd>
          row {r} · column {c} · box ({boxR},{boxC})
        </dd>
      </div>
      <div>
        <dt>Role</dt>
        <dd>{isClue ? "Public clue — visible to verifier" : "Witness — proves zero-knowledge"}</dd>
      </div>
      <div>
        <dt>Value</dt>
        <dd>{cellValue === 0 ? "—" : cellValue}</dd>
      </div>
      <div>
        <dt>In-circuit work</dt>
        <dd>
          1 in-range polynomial (8 multiplications) · 1 squared
          witness · 3 group sums · 3 group sum-of-squares · 1 clue
          match
        </dd>
      </div>
    </dl>
  );
}

function buildValidReplay(e: Evidence): string[] {
  return [
    "    Compiling mosaic-demo-sudoku v" + e.workspace_version,
    "    Finished `test` profile [unoptimized + debuginfo]",
    "     Running unittests src/lib.rs",
    "",
    "running 1 test",
    `test prover::tests::end_to_end_setup_prove_verify_via_mosaic ...`,
    `    1. arkworks Groth16 setup ........... ${e.timings.setup_ms} ms`,
    `    2. arkworks Groth16 prove ........... ${e.timings.prove_ms} ms`,
    `    3. arkworks::Groth16::verify ........ ${e.timings.verify_arkworks_ms} ms → ${e.verifier_outcomes.arkworks_valid}`,
    `    4. mosaic_serde::ArkworksCodec::encode_*  → canonical bytes`,
    `       vk.bin           = ${e.sizes_bytes.vk} B   sha256:${e.digests_sha256.vk.slice(0, 16)}…`,
    `       proof_valid.bin  = ${e.sizes_bytes.proof} B    sha256:${e.digests_sha256.proof_valid.slice(0, 16)}…`,
    `       public_inputs.bin= ${e.sizes_bytes.public_inputs} B   sha256:${e.digests_sha256.public_inputs.slice(0, 16)}…`,
    `    5. mosaic_groth16::Groth16Verifier::verify`,
    `       backend = HostBackend (same syscall ABI as Solana SBF)`,
    `       result  = Ok(())`,
    `       elapsed = ${e.timings.verify_mosaic_valid_ms} ms`,
    "test prover::tests::end_to_end_setup_prove_verify_via_mosaic ... ok",
    "",
    "test result: ok. 1 passed; 0 failed; 0 ignored",
  ];
}

function buildTamperedReplay(e: Evidence): string[] {
  const errToken = e.verifier_outcomes.mosaic_tampered.replace("reject:", "");
  return [
    "    Compiling mosaic-demo-sudoku v" + e.workspace_version,
    "    Finished `test` profile [unoptimized + debuginfo]",
    "     Running unittests src/lib.rs",
    "",
    "running 1 test",
    `test prover::tests::tampered_proof_rejects_via_mosaic ...`,
    `    1. start from valid proof bytes`,
    `       sha256:${e.digests_sha256.proof_valid}`,
    `    2. flip the low bit of proof.a's first byte (byte offset 0)`,
    `       sha256:${e.digests_sha256.proof_tampered}`,
    `    3. mosaic_groth16::Groth16Verifier::verify`,
    `       backend = HostBackend`,
    `       result  = Err(${errToken})`,
    `       elapsed = ${e.timings.verify_mosaic_tampered_ms} ms`,
    `    4. assertion: result.is_err() ............... PASS`,
    `       (the verifier MUST reject; soundness depends on it)`,
    "test prover::tests::tampered_proof_rejects_via_mosaic ... ok",
    "",
    "test result: ok. 1 passed; 0 failed; 0 ignored",
  ];
}
